version: "3"
services:
  portainer:
    image: portainer/portainer-ce:2.18.1
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  data: