---
- name: Update os
  hosts: servers
  become: true

  tasks:
  - name: Add the overlay module
    community.general.modprobe:
      name: overlay
      state: present

  - name: Add the br_netfilter module
    community.general.modprobe:
      name: br_netfilter
      state: present

  - name: Add config for module automatic loading
    ansible.builtin.copy:
      content: |
        overlay
        br_netfilter
      dest: /etc/modules-load.d/k8s.conf

  - name: Copy using inline content
    ansible.builtin.copy:
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
      dest: /etc/sysctl.d/kubernetes.conf

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /etc/containerd 
      state: directory
      mode: '0755'

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /etc/containerd 
      state: directory
      mode: '0755'

  - name: Run command to create the default config for containerd
    ansible.builtin.command: containerd config default | sudo tee /etc/containerd/config.toml