---
- name: Update os
  hosts: servers
  become: true

  tasks:

  - name: Enable the kubelet
    ansible.builtin.systemd_service:
      name: kubelet
      state: started
      enabled: true

  - name: Enable containerd
    ansible.builtin.systemd_service:
      name: containerd
      state: started
      enabled: true

  - name: Enable qemu agent
    ansible.builtin.systemd_service:
      name: qemu-guest-agent.service