---
- name: Update os
  hosts: servers

  tasks:
  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
    become: true
    become_user: root

  - name: Upgrade the OS (apt-get dist-upgrade)
    ansible.builtin.apt:
      upgrade: dist
    become: true
    become_user: root

    # more info https://stackoverflow.com/questions/71585303/how-can-i-manage-keyring-files-in-trusted-gpg-d-with-ansible-playbook-since-apt
  - name: Add Example GPG key
    ansible.builtin.get_url:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      dest: /etc/apt/trusted.gpg.d/cgoogle.asc
      mode: '0644'
      force: true
    become: true
    become_user: root

  - name: Add specified repository into sources list
    ansible.builtin.apt_repository:
      repo: deb  [signed-by=/etc/apt/trusted.gpg.d/cgoogle.asc] http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
    become: true
    become_user: root

  - name: Install a list of packages
    ansible.builtin.apt:
      pkg:
      - kubelet
      - kubeadm
      - kubectl
    become: true
    become_user: root

  - name: Hold kubelet
    ansible.builtin.dpkg_selections:
      name: kubelet
      selection: hold
    become: true
    become_user: root

  - name: Hold kubeadm
    ansible.builtin.dpkg_selections:
      name: kubeadm
      selection: hold
    become: true
    become_user: root

  - name: Hold kubectl
    ansible.builtin.dpkg_selections:
      name: kubectl
      selection: hold
    become: true
    become_user: root
