apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sandbox
  labels:
    app: web-nginx
  name: web-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {} 