apiVersion: v1
kind: Service
metadata:
  namespace: sandbox
  name: service-nginx
spec:
  type: NodePort
  selector:
    app: web-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001